### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by stuartpb** [pulltool/pulltool-chrome-app#1]
Here's what I'm thinking (using YAML syntax and Tabalanche as an example):

```
source:
  zip: https://github.com/tabalanche/tabalanche-extension/archive/unstable.zip
extension:
  shim:
    manifest:
      name: Unstable Tabalanche
      icons:
        "16": images/tabalanche-unstable-16px.png
        "48": images/tabalanche-unstable-48px.png
        "128": images/tabalanche-unstable-128px-20pxborder.png
      browser_action:
        default_icon:
          "19": images/tabalanche-unstable-19px.png
          "38": images/tabalanche-unstable-38px.png
        default_title: Unstable Tabalanche
```

**Comment by stuartpb** [comment]
Actually, since extension management isn't allowed for Chrome apps (ugh), I'm probably going to do something more like this (which can be generalized):

```
patch:
  json:
    manifest.json:
      name: Unstable Tabalanche
      icons:
        "16": images/tabalanche-unstable-16px.png
        "48": images/tabalanche-unstable-48px.png
        "128": images/tabalanche-unstable-128px-20pxborder.png
      browser_action:
        default_icon:
          "19": images/tabalanche-unstable-19px.png
          "38": images/tabalanche-unstable-38px.png
        default_title: Unstable Tabalanche
```

**Comment by stuartpb** [comment]
Actually, to keep the JSON patching flexible, there should probably be a layer like "set" that sets keys to values (with room for future extensions like "append" and "merge"). Maybe call it "values" or "properties".

**Comment by stuartpb** [comment]
Okay, so here's the new sample schema:

``` yaml
sources:
- url: https://path/to/whatever.zip
  slice:
  - from: subfolder-in-zip/deeper-subfolder #defaults to root
    to: different-sublocation #defaults to root
tags: [extension]
patch:
  files:
    manifest.json:
      set: {name: "Example (Development)"}
    icon.png:
      color: [invert]
```
